export const StoreQueryTagEnum = {
  USER: "USER",
};
export const medicalSpecialtiesOptions = [
  { value: "Acupuncturist", label: "Acupuncturist" },
  { value: "Allergist / Immunologist", label: "Allergist / Immunologist" },
  { value: "Anesthesiologist", label: "Anesthesiologist" },
  { value: "Audiologist", label: "Audiologist" },
  { value: "Cardiologist / Heart Doctor", label: "Cardiologist / Heart Doctor" },
  { value: "Cardiothoracic Surgeon", label: "Cardiothoracic Surgeon" },
  { value: "Chiropractor", label: "Chiropractor" },
  { value: "Colorectal Surgeon", label: "Colorectal Surgeon" },
  { value: "Cosmetic Dentist", label: "Cosmetic Dentist" },
  { value: "Dentist", label: "Dentist" },
  { value: "Dermatologist", label: "Dermatologist" },
  { value: "Dietitian / Nutritionist", label: "Dietitian / Nutritionist" },
  { value: "Ear, Nose & Throat Doctor / ENT / Otolaryngologist", label: "Ear, Nose & Throat Doctor / ENT / Otolaryngologist" },
  { value: "Emergency Care Physician", label: "Emergency Care Physician" },
  { value: "Endocrinologist / Diabetes Specialist", label: "Endocrinologist / Diabetes Specialist" },
  { value: "Endodontist", label: "Endodontist" },
  { value: "Eye Doctor", label: "Eye Doctor" },
  { value: "Gastroenterologist", label: "Gastroenterologist" },
  { value: "Geneticist / Genetics Specialist", label: "Geneticist / Genetics Specialist" },
  { value: "Geriatrician", label: "Geriatrician" },
  { value: "Hearing Specialist", label: "Hearing Specialist" },
  { value: "Hematologist / Blood Specialist", label: "Hematologist / Blood Specialist" },
  { value: "Infectious Disease Specialist", label: "Infectious Disease Specialist" },
  { value: "Infertility Specialist", label: "Infertility Specialist" },
  { value: "Internist / Internal Medicine Specialist", label: "Internist / Internal Medicine Specialist" },
  { value: "Midwife", label: "Midwife" },
  { value: "Naturopathic Doctor", label: "Naturopathic Doctor" },
  { value: "Nephrologist / Kidney Specialist", label: "Nephrologist / Kidney Specialist" },
  { value: "Neurologist / Headache Specialist", label: "Neurologist / Headache Specialist" },
  { value: "Neurosurgeon", label: "Neurosurgeon" },
  { value: "OB-GYN (Obstetrician-Gynecologist)", label: "OB-GYN (Obstetrician-Gynecologist)" },
  { value: "Oncologist", label: "Oncologist" },
  { value: "Ophthalmologist", label: "Ophthalmologist" },
  { value: "Optometrist", label: "Optometrist" },
  { value: "Oral Surgeon", label: "Oral Surgeon" },
  { value: "Orthodontist", label: "Orthodontist" },
  { value: "Orthopedic Surgeon / Orthopedist", label: "Orthopedic Surgeon / Orthopedist" },
  { value: "Pain Management Specialist", label: "Pain Management Specialist" },
  { value: "Pediatric Dentist", label: "Pediatric Dentist" },
  { value: "Pediatric Surgeon", label: "Pediatric Surgeon" },
  { value: "Pediatrician", label: "Pediatrician" },
  { value: "Periodontist", label: "Periodontist" },
  { value: "Physiatrist / Physical Medicine Specialist", label: "Physiatrist / Physical Medicine Specialist" },
  { value: "Physical Therapist", label: "Physical Therapist" },
  { value: "Plastic Surgeon", label: "Plastic Surgeon" },
  { value: "Podiatrist / Foot and Ankle Specialist", label: "Podiatrist / Foot and Ankle Specialist" },
  { value: "Primary Care Physician (PCP) / Family Practice Physician", label: "Primary Care Physician (PCP) / Family Practice Physician" },
  { value: "Prosthodontist", label: "Prosthodontist" },
  { value: "Psychiatrist", label: "Psychiatrist" },
  { value: "Psychologist", label: "Psychologist" },
  { value: "Pulmonologist / Lung Doctor", label: "Pulmonologist / Lung Doctor" },
  { value: "Radiologist", label: "Radiologist" },
  { value: "Rheumatologist", label: "Rheumatologist" },
  { value: "Sleep Medicine Specialist", label: "Sleep Medicine Specialist" },
  { value: "Sports Medicine Specialist", label: "Sports Medicine Specialist" },
  { value: "Surgeon", label: "Surgeon" },
  { value: "Therapist / Counselor", label: "Therapist / Counselor" },
  { value: "Urgent Care Specialist", label: "Urgent Care Specialist" },
  { value: "Urological Surgeon", label: "Urological Surgeon" },
  { value: "Urologist", label: "Urologist" },
  { value: "Vascular Surgeon", label: "Vascular Surgeon" },
];