export const StoreQueryTagEnum = {
  USER: "USER",
};
export const medicalSpecialtiesOptions = [
  { value: "unsure", label: "I am unsure" },
  { value: "Acupuncturist", label: "Acupuncturist" },
  { value: "Allergist / Immunologist", label: "Allergist / Immunologist" },
  { value: "Anesthesiologist", label: "Anesthesiologist" },
  { value: "Audiologist", label: "Audiologist" },
  { value: "Cardiologist / Heart Doctor", label: "Cardiologist / Heart Doctor" },
  { value: "Cardiothoracic Surgeon", label: "Cardiothoracic Surgeon" },
  { value: "Chiropractor", label: "Chiropractor" },
  { value: "Colorectal Surgeon", label: "Colorectal Surgeon" },
  { value: "Cosmetic Dentist", label: "Cosmetic Dentist" },
  { value: "Dentist", label: "Dentist" },
  { value: "Dermatologist", label: "Dermatologist" },
  { value: "Dietitian / Nutritionist", label: "Dietitian / Nutritionist" },
  { value: "Ear, Nose & Throat Doctor / ENT / Otolaryngologist", label: "Ear, Nose & Throat Doctor / ENT / Otolaryngologist" },
  { value: "Emergency Care Physician", label: "Emergency Care Physician" },
  { value: "Endocrinologist / Diabetes Specialist", label: "Endocrinologist / Diabetes Specialist" },
  { value: "Endodontist", label: "Endodontist" },
  { value: "Eye Doctor", label: "Eye Doctor" },
  { value: "Gastroenterologist", label: "Gastroenterologist" },
  { value: "Geneticist / Genetics Specialist", label: "Geneticist / Genetics Specialist" },
  { value: "Geriatrician", label: "Geriatrician" },
  { value: "Hearing Specialist", label: "Hearing Specialist" },
  { value: "Hematologist / Blood Specialist", label: "Hematologist / Blood Specialist" },
  { value: "Infectious Disease Specialist", label: "Infectious Disease Specialist" },
  { value: "Infertility Specialist", label: "Infertility Specialist" },
  { value: "Internist / Internal Medicine Specialist", label: "Internist / Internal Medicine Specialist" },
  { value: "Midwife", label: "Midwife" },
  { value: "Naturopathic Doctor", label: "Naturopathic Doctor" },
  { value: "Nephrologist / Kidney Specialist", label: "Nephrologist / Kidney Specialist" },
  { value: "Neurologist / Headache Specialist", label: "Neurologist / Headache Specialist" },
  { value: "Neurosurgeon", label: "Neurosurgeon" },
  { value: "OB-GYN (Obstetrician-Gynecologist)", label: "OB-GYN (Obstetrician-Gynecologist)" },
  { value: "Oncologist", label: "Oncologist" },
  { value: "Ophthalmologist", label: "Ophthalmologist" },
  { value: "Optometrist", label: "Optometrist" },
  { value: "Oral Surgeon", label: "Oral Surgeon" },
  { value: "Orthodontist", label: "Orthodontist" },
  { value: "Orthopedic Surgeon / Orthopedist", label: "Orthopedic Surgeon / Orthopedist" },
  { value: "Other", label: "Other" },
  { value: "Pain Management Specialist", label: "Pain Management Specialist" },
  { value: "Pediatric Dentist", label: "Pediatric Dentist" },
  { value: "Pediatric Surgeon", label: "Pediatric Surgeon" },
  { value: "Pediatrician", label: "Pediatrician" },
  { value: "Periodontist", label: "Periodontist" },
  { value: "Physiatrist / Physical Medicine Specialist", label: "Physiatrist / Physical Medicine Specialist" },
  { value: "Physical Therapist", label: "Physical Therapist" },
  { value: "Plastic Surgeon", label: "Plastic Surgeon" },
  { value: "Podiatrist / Foot and Ankle Specialist", label: "Podiatrist / Foot and Ankle Specialist" },
  { value: "Primary Care Physician (PCP) / Family Practice Physician", label: "Primary Care Physician (PCP) / Family Practice Physician" },
  { value: "Primary Care Physician (PCP)", label: "Prescription / Refill" },
  { value: "Prosthodontist", label: "Prosthodontist" },
  { value: "Psychiatrist", label: "Psychiatrist" },
  { value: "Psychologist", label: "Psychologist" },
  { value: "Pulmonologist / Lung Doctor", label: "Pulmonologist / Lung Doctor" },
  { value: "Radiologist", label: "Radiologist" },
  { value: "Rheumatologist", label: "Rheumatologist" },
  { value: "Sleep Medicine Specialist", label: "Sleep Medicine Specialist" },
  { value: "Sports Medicine Specialist", label: "Sports Medicine Specialist" },
  { value: "Surgeon", label: "Surgeon" },
  { value: "Therapist / Counselor", label: "Therapist / Counselor" },
  { value: "Urgent Care Specialist", label: "Urgent Care Specialist" },
  { value: "Urological Surgeon", label: "Urological Surgeon" },
  { value: "Urologist", label: "Urologist" },
  { value: "Vascular Surgeon", label: "Vascular Surgeon" },
];
export const insuranceCarrierOptions = 
  [
    {"value": "1199SEIU", "label": "1199SEIU"},
    {"value": "1st Agency", "label": "1st Agency"},
    {"value": "20/20 Eyecare Plan", "label": "20/20 Eyecare Plan"},
    {"value": "AARP", "label": "AARP"},
    {"value": "ACE", "label": "ACE"},
    {"value": "AIG", "label": "AIG"},
    {"value": "APWU", "label": "APWU"},
    {"value": "ATRIO Health Plans", "label": "ATRIO Health Plans"},
    {"value": "AVMA Life", "label": "AVMA Life"},
    {"value": "Absolute Total Care", "label": "Absolute Total Care"},
    {"value": "Access Medicare (NY)", "label": "Access Medicare (NY)"},
    {"value": "Accountable Health Plan of Ohio", "label": "Accountable Health Plan of Ohio"},
    {"value": "Advanced Health", "label": "Advanced Health"},
    {"value": "AdvantageMD", "label": "AdvantageMD"},
    {"value": "Advantica", "label": "Advantica"},
    {"value": "Advent Health", "label": "Advent Health"},
    {"value": "Adventist Health", "label": "Adventist Health"},
    {"value": "Advocate Health Care", "label": "Advocate Health Care"},
    {"value": "Aetna", "label": "Aetna"},
    {"value": "Aetna Better Health", "label": "Aetna Better Health"},
    {"value": "Affinity Health Plan", "label": "Affinity Health Plan"},
    {"value": "AgeRight Advantage", "label": "AgeRight Advantage"},
    {"value": "AgeWell New York", "label": "AgeWell New York"},
    {"value": "Agile Health Insurance", "label": "Agile Health Insurance"},
    {"value": "Alameda Alliance for Health", "label": "Alameda Alliance for Health"},
    {"value": "Aliera Health Care", "label": "Aliera Health Care"},
    {"value": "Alignment Health Plan", "label": "Alignment Health Plan"},
    {"value": "All Savers Insurance", "label": "All Savers Insurance"},
    {"value": "AllCare Health", "label": "AllCare Health"},
    {"value": "AllState", "label": "AllState"},
    {"value": "Allegiance Life and Health", "label": "Allegiance Life and Health"},
    {"value": "Alliant Health Plans", "label": "Alliant Health Plans"},
    {"value": "Allianz Worldwide Care", "label": "Allianz Worldwide Care"},
    {"value": "Allwell", "label": "Allwell"},
    {"value": "AlohaCare", "label": "AlohaCare"},
    {"value": "AlphaCare", "label": "AlphaCare"},
    {"value": "AltaMed Senior BuenaCare (PACE)", "label": "AltaMed Senior BuenaCare (PACE)"},
    {"value": "Alterwood Advantage", "label": "Alterwood Advantage"},
    {"value": "Altius (Coventry Health Care)", "label": "Altius (Coventry Health Care)"},
    {"value": "AlwaysCare", "label": "AlwaysCare"},
    {"value": "Ambetter", "label": "Ambetter"},
    {"value": "AmeriGroup", "label": "AmeriGroup"},
    {"value": "AmeriHealth", "label": "AmeriHealth"},
    {"value": "AmeriHealth Caritas", "label": "AmeriHealth Caritas"},
    {"value": "America's 1st Choice", "label": "America's 1st Choice"},
    {"value": "American Behavioral", "label": "American Behavioral"},
    {"value": "American Eldercare", "label": "American Eldercare"},
    {"value": "American Healthcare Alliance", "label": "American Healthcare Alliance"},
    {"value": "American Maritime Officers Plans", "label": "American Maritime Officers Plans"},
    {"value": "American Republic Insurance Company", "label": "American Republic Insurance Company"},
    {"value": "Amida Care", "label": "Amida Care"},
    {"value": "Amita Health", "label": "Amita Health"},
    {"value": "Amplifon Hearing Health Care", "label": "Amplifon Hearing Health Care"},
    {"value": "Anthem Blue Cross", "label": "Anthem Blue Cross"},
    {"value": "Anthem Blue Cross Blue Shield", "label": "Anthem Blue Cross Blue Shield"},
    {"value": "Apostrophe", "label": "Apostrophe"},
    {"value": "ArchCare", "label": "ArchCare"},
    {"value": "Arise Health Plan", "label": "Arise Health Plan"},
    {"value": "Arizona Complete Health", "label": "Arizona Complete Health"},
    {"value": "Arizona Foundation for Medical Care", "label": "Arizona Foundation for Medical Care"},
    {"value": "Arkansas Blue Cross Blue Shield", "label": "Arkansas Blue Cross Blue Shield"},
    {"value": "Arkansas Total Care", "label": "Arkansas Total Care"},
    {"value": "Ascension Complete", "label": "Ascension Complete"},
    {"value": "Ascension Health", "label": "Ascension Health"},
    {"value": "Aspire Health Plan", "label": "Aspire Health Plan"},
    {"value": "Assurant Employee Benefits", "label": "Assurant Employee Benefits"},
    {"value": "Assurant Health", "label": "Assurant Health"},
    {"value": "Asuris Northwest Health", "label": "Asuris Northwest Health"},
    {"value": "Aultcare", "label": "Aultcare"},
    {"value": "AvMed", "label": "AvMed"},
    {"value": "Avera Health Plans", "label": "Avera Health Plans"},
    {"value": "Avesis", "label": "Avesis"},
    {"value": "BMC HealthNet Plan", "label": "BMC HealthNet Plan"},
    {"value": "Banker's Life", "label": "Banker's Life"},
    {"value": "Banner Health", "label": "Banner Health"},
    {"value": "Baptist Health Plan", "label": "Baptist Health Plan"},
    {"value": "BayCarePlus Medicare Advantage", "label": "BayCarePlus Medicare Advantage"},
    {"value": "Baylor Scott & White Health Plan", "label": "Baylor Scott & White Health Plan"},
    {"value": "Beaumont Employee Health Plan", "label": "Beaumont Employee Health Plan"},
    {"value": "Beech Street", "label": "Beech Street"},
    {"value": "Best Choice Plus", "label": "Best Choice Plus"},
    {"value": "Best Doctors Insurance", "label": "Best Doctors Insurance"},
    {"value": "Best Life And Health", "label": "Best Life And Health"},
    {"value": "Better Health (Florida Medicaid)", "label": "Better Health (Florida Medicaid)"},
    {"value": "Blue Choice Health Plan", "label": "Blue Choice Health Plan"},
    {"value": "Blue Cross Blue Shield", "label": "Blue Cross Blue Shield"},
    {"value": "Blue Cross Blue Shield Federal Employee Program", "label": "Blue Cross Blue Shield Federal Employee Program"},
    {"value": "Blue Cross Blue Shield of Alabama", "label": "Blue Cross Blue Shield of Alabama"},
    {"value": "Blue Cross Blue Shield of Arizona", "label": "Blue Cross Blue Shield of Arizona"},
    {"value": "Blue Cross Blue Shield of Georgia", "label": "Blue Cross Blue Shield of Georgia"},
    {"value": "Blue Cross Blue Shield of Illinois", "label": "Blue Cross Blue Shield of Illinois"},
    {"value": "Blue Cross Blue Shield of Kansas", "label": "Blue Cross Blue Shield of Kansas"},
    {"value": "Blue Cross Blue Shield of Kansas City", "label": "Blue Cross Blue Shield of Kansas City"},
    {"value": "Blue Cross Blue Shield of Louisiana", "label": "Blue Cross Blue Shield of Louisiana"},
    {"value": "Blue Cross Blue Shield of Massachusetts", "label": "Blue Cross Blue Shield of Massachusetts"},
    {"value": "Blue Cross Blue Shield of Michigan", "label": "Blue Cross Blue Shield of Michigan"},
    {"value": "Blue Cross Blue Shield of Minnesota", "label": "Blue Cross Blue Shield of Minnesota"},
    {"value": "Blue Cross Blue Shield of Mississippi", "label": "Blue Cross Blue Shield of Mississippi"},
    {"value": "Blue Cross Blue Shield of Montana", "label": "Blue Cross Blue Shield of Montana"},
    {"value": "Blue Cross Blue Shield of Nebraska", "label": "Blue Cross Blue Shield of Nebraska"},
    {"value": "Blue Cross Blue Shield of New Mexico", "label": "Blue Cross Blue Shield of New Mexico"},
    {"value": "Blue Cross Blue Shield of North Carolina", "label": "Blue Cross Blue Shield of North Carolina"},
    {"value": "Blue Cross Blue Shield of North Dakota", "label": "Blue Cross Blue Shield of North Dakota"},
    {"value": "Blue Cross Blue Shield of Oklahoma", "label": "Blue Cross Blue Shield of Oklahoma"},
    {"value": "Blue Cross Blue Shield of Rhode Island", "label": "Blue Cross Blue Shield of Rhode Island"},
    {"value": "Blue Cross Blue Shield of South Carolina", "label": "Blue Cross Blue Shield of South Carolina"},
    {"value": "Blue Cross Blue Shield of Tennessee", "label": "Blue Cross Blue Shield of Tennessee"},
    {"value": "Blue Cross Blue Shield of Texas", "label": "Blue Cross Blue Shield of Texas"},
    {"value": "Blue Cross Blue Shield of Vermont", "label": "Blue Cross Blue Shield of Vermont"},
    {"value": "Blue Cross Blue Shield of Wyoming", "label": "Blue Cross Blue Shield of Wyoming"},
    {"value": "Blue Cross of Idaho", "label": "Blue Cross of Idaho"},
    {"value": "Blue Cross of Northeastern Pennsylvania", "label": "Blue Cross of Northeastern Pennsylvania"},
    {"value": "Blue Shield of California", "label": "Blue Shield of California"},
    {"value": "Blue Shield of Northeastern New York", "label": "Blue Shield of Northeastern New York"},
    {"value": "Brand New Day", "label": "Brand New Day"},
    {"value": "Braven Health (Horizon Blue Cross Blue Shield of New Jersey)", "label": "Braven Health (Horizon Blue Cross Blue Shield of New Jersey)"},
    {"value": "BridgeSpan", "label": "BridgeSpan"},
    {"value": "Bridgeway Health Solutions", "label": "Bridgeway Health Solutions"},
    {"value": "Bright Health", "label": "Bright Health"},
    {"value": "Buckeye Health Plan", "label": "Buckeye Health Plan"},
    {"value": "CBA Blue", "label": "CBA Blue"},
    {"value": "CDPHP", "label": "CDPHP"},
    {"value": "CHAMPVA", "label": "CHAMPVA"},
    {"value": "CHP Group", "label": "CHP Group"},
    {"value": "CHRISTUS Health Plan", "label": "CHRISTUS Health Plan"},
    {"value": "CalOptima", "label": "CalOptima"},
    {"value": "CalPERS", "label": "CalPERS"},
    {"value": "CalViva Health", "label": "CalViva Health"},
    {"value": "California Foundation for Medical Care", "label": "California Foundation for Medical Care"},
    {"value": "California Health and Wellness", "label": "California Health and Wellness"},
    {"value": "Calvos", "label": "Calvos"},
    {"value": "Cambridge Health Alliance (CHA)", "label": "Cambridge Health Alliance (CHA)"},
    {"value": "Capital Blue Cross", "label": "Capital Blue Cross"},
    {"value": "Capital Health Plan", "label": "Capital Health Plan"},
    {"value": "Care Improvement Plus", "label": "Care Improvement Plus"},
    {"value": "Care N' Care", "label": "Care N' Care"},
    {"value": "Care1st", "label": "Care1st"},
    {"value": "CareConnect", "label": "CareConnect"},
    {"value": "CareFirst Blue Cross Blue Shield  (Health)", "label": "CareFirst Blue Cross Blue Shield  (Health)"},
    {"value": "CareMore", "label": "CareMore"},
    {"value": "CareOregon", "label": "CareOregon"},
    {"value": "CarePartners of Connecticut", "label": "CarePartners of Connecticut"},
    {"value": "CarePlus Health Plans (Florida Medicare)", "label": "CarePlus Health Plans (Florida Medicare)"},
    {"value": "CareSource", "label": "CareSource"},
    {"value": "Carelon Behavioral Health (fka Beacon Health)", "label": "Carelon Behavioral Health (fka Beacon Health)"},
    {"value": "Cascade Health Alliance", "label": "Cascade Health Alliance"},
    {"value": "Caterpillar", "label": "Caterpillar"},
    {"value": "CeltiCare Health Plan", "label": "CeltiCare Health Plan"},
    {"value": "CenCal Health", "label": "CenCal Health"},
    {"value": "Cenpatico", "label": "Cenpatico"},
    {"value": "Centennial Care", "label": "Centennial Care"},
    {"value": "Center for Elders' Independence (PACE)", "label": "Center for Elders' Independence (PACE)"},
    {"value": "CenterLight Healthcare", "label": "CenterLight Healthcare"},
    {"value": "Centers Plan for Healthy Living", "label": "Centers Plan for Healthy Living"},
    {"value": "Centivo", "label": "Centivo"},
    {"value": "Centra Health", "label": "Centra Health"},
    {"value": "Central California Alliance for Health", "label": "Central California Alliance for Health"},
    {"value": "Central Health Plan of California", "label": "Central Health Plan of California"},
    {"value": "Century Healthcare - CHC", "label": "Century Healthcare - CHC"},
    {"value": "Children's Community Health Plan", "label": "Children's Community Health Plan"},
    {"value": "Children's Medical Center Health Plan", "label": "Children's Medical Center Health Plan"},
    {"value": "Children's Medical Services (CMS)", "label": "Children's Medical Services (CMS)"},
    {"value": "Chinese Community Health Plan", "label": "Chinese Community Health Plan"},
    {"value": "Choice Care Network", "label": "Choice Care Network"},
    {"value": "Christian Healthcare Ministries", "label": "Christian Healthcare Ministries"},
    {"value": "Cigna", "label": "Cigna"},
    {"value": "Cigna-HealthSpring", "label": "Cigna-HealthSpring"},
    {"value": "Clarion Health", "label": "Clarion Health"},
    {"value": "Clark County Self-Funded Health", "label": "Clark County Self-Funded Health"},
    {"value": "Clear Spring Health", "label": "Clear Spring Health"},
    {"value": "Clements Worldwide", "label": "Clements Worldwide"},
    {"value": "Cleveland Clinic Employee Health Plan", "label": "Cleveland Clinic Employee Health Plan"},
    {"value": "Clover Health", "label": "Clover Health"},
    {"value": "Cofinity", "label": "Cofinity"},
    {"value": "Colorado Access", "label": "Colorado Access"},
    {"value": "Columbia Pacific CCO", "label": "Columbia Pacific CCO"},
    {"value": "Columbia United Providers", "label": "Columbia United Providers"},
    {"value": "ComPsych", "label": "ComPsych"},
    {"value": "Common Ground Healthcare Cooperative", "label": "Common Ground Healthcare Cooperative"},
    {"value": "Commonwealth Care Alliance", "label": "Commonwealth Care Alliance"},
    {"value": "Community Behavioral Health", "label": "Community Behavioral Health"},
    {"value": "Community Care Alliance of Illinois", "label": "Community Care Alliance of Illinois"},
    {"value": "Community Care Associates", "label": "Community Care Associates"},
    {"value": "Community Care Behavioral Health Organization", "label": "Community Care Behavioral Health Organization"},
    {"value": "Community Care Plan", "label": "Community Care Plan"},
    {"value": "Community Care of North Carolina", "label": "Community Care of North Carolina"},
    {"value": "Community Eye Care", "label": "Community Eye Care"},
    {"value": "Community First Health Plans", "label": "Community First Health Plans"},
    {"value": "Community Health Choice", "label": "Community Health Choice"},
    {"value": "Community Health Group", "label": "Community Health Group"},
    {"value": "Community Health Options", "label": "Community Health Options"},
    {"value": "Community Health Partners", "label": "Community Health Partners"},
    {"value": "Community Health Plan of Washington", "label": "Community Health Plan of Washington"},
    {"value": "CommunityCare of Oklahoma", "label": "CommunityCare of Oklahoma"},
    {"value": "CompBenefits", "label": "CompBenefits"},
    {"value": "Companion Life", "label": "Companion Life"},
    {"value": "Comprehensive Health Insurance Plan (CHIP) of Illinois", "label": "Comprehensive Health Insurance Plan (CHIP) of Illinois"},
    {"value": "Comprehensive Medical and Dental Program (CMDP)", "label": "Comprehensive Medical and Dental Program (CMDP)"},
    {"value": "Connect Care", "label": "Connect Care"},
    {"value": "ConnectiCare", "label": "ConnectiCare"},
    {"value": "Consolidated Health Plans", "label": "Consolidated Health Plans"},
    {"value": "Constitution Life", "label": "Constitution Life"},
    {"value": "Consumer Health Network", "label": "Consumer Health Network"},
    {"value": "Contra Costa Health Plan", "label": "Contra Costa Health Plan"},
    {"value": "Cook Children's Health Plan", "label": "Cook Children's Health Plan"},
    {"value": "Coordinated Care Health", "label": "Coordinated Care Health"},
    {"value": "Corvel", "label": "Corvel"},
    {"value": "CountyCare (Cook County)", "label": "CountyCare (Cook County)"},
    {"value": "Coventry Health Care", "label": "Coventry Health Care"},
    {"value": "Cox HealthPlans", "label": "Cox HealthPlans"},
    {"value": "Create", "label": "Create"},
    {"value": "Crystal Run Health Plans", "label": "Crystal Run Health Plans"},
    {"value": "Culinary Health Fund", "label": "Culinary Health Fund"},
    {"value": "CuraLinc Healthcare", "label": "CuraLinc Healthcare"},
    {"value": "Curative", "label": "Curative"},
    {"value": "DC Medicaid", "label": "DC Medicaid"},
    {"value": "DMC Care", "label": "DMC Care"},
    {"value": "DOCS (Doctors of the Oregon South Coast)", "label": "DOCS (Doctors of the Oregon South Coast)"},
    {"value": "DavidShield", "label": "DavidShield"},
    {"value": "Davis Vision", "label": "Davis Vision"},
    {"value": "Deaconess Health Plans", "label": "Deaconess Health Plans"},
    {"value": "Dean Health Plan", "label": "Dean Health Plan"},
    {"value": "Dell Children's Health Plan", "label": "Dell Children's Health Plan"},
    {"value": "Denver Health Medical Plan", "label": "Denver Health Medical Plan"},
    {"value": "Department of Medical Assistance Services", "label": "Department of Medical Assistance Services"},
    {"value": "Deseret Mutual", "label": "Deseret Mutual"},
    {"value": "Devon Health Services", "label": "Devon Health Services"},
    {"value": "Devoted Health", "label": "Devoted Health"},
    {"value": "Dimension Health", "label": "Dimension Health"},
    {"value": "Doctors HealthCare Plans", "label": "Doctors HealthCare Plans"},
    {"value": "Driscoll Health Plan", "label": "Driscoll Health Plan"},
    {"value": "EHP Significa", "label": "EHP Significa"},
    {"value": "EMI Health", "label": "EMI Health"},
    {"value": "ESSENCE Healthcare", "label": "ESSENCE Healthcare"},
    {"value": "Eastern Oregon Coordinated Care Organization", "label": "Eastern Oregon Coordinated Care Organization"},
    {"value": "Easy Choice Health Plan (California)", "label": "Easy Choice Health Plan (California)"},
    {"value": "Easy Choice Health Plan of New York", "label": "Easy Choice Health Plan of New York"},
    {"value": "El Paso First Health Plans", "label": "El Paso First Health Plans"},
    {"value": "Elderplan", "label": "Elderplan"},
    {"value": "EmblemHealth", "label": "EmblemHealth"},
    {"value": "EmblemHealth (formerly known as GHI)", "label": "EmblemHealth (formerly known as GHI)"},
    {"value": "EmblemHealth (formerly known as HIP)", "label": "EmblemHealth (formerly known as HIP)"},
    {"value": "Emory Health Care Plan", "label": "Emory Health Care Plan"},
    {"value": "Empire Blue Cross Blue Shield (Health)", "label": "Empire Blue Cross Blue Shield (Health)"},
    {"value": "Empire BlueCross BlueShield HealthPlus", "label": "Empire BlueCross BlueShield HealthPlus"},
    {"value": "Empire Plan", "label": "Empire Plan"},
    {"value": "Empower Healthcare Solutions", "label": "Empower Healthcare Solutions"},
    {"value": "Encore Health Network", "label": "Encore Health Network"},
    {"value": "Envolve Benefit Options", "label": "Envolve Benefit Options"},
    {"value": "Eon Health", "label": "Eon Health"},
    {"value": "Epic Hearing Health Care", "label": "Epic Hearing Health Care"},
    {"value": "Erickson Advantage", "label": "Erickson Advantage"},
    {"value": "EverCare", "label": "EverCare"},
    {"value": "Evergreen Health Cooperative", "label": "Evergreen Health Cooperative"},
    {"value": "Evolutions Healthcare Systems", "label": "Evolutions Healthcare Systems"},
    {"value": "Excellus Blue Cross Blue Shield", "label": "Excellus Blue Cross Blue Shield"},
    {"value": "Experience HealthND", "label": "Experience HealthND"},
    {"value": "Extended Managed Long Term Care", "label": "Extended Managed Long Term Care"},
    {"value": "EyeMed", "label": "EyeMed"},
    {"value": "Eyetopia Vision Care", "label": "Eyetopia Vision Care"},
    {"value": "Fallon Community Health Plan (FCHP)", "label": "Fallon Community Health Plan (FCHP)"},
    {"value": "Family Health Network", "label": "Family Health Network"},
    {"value": "FamilyCare Health Plans", "label": "FamilyCare Health Plans"},
    {"value": "Fidelis Care (NY)", "label": "Fidelis Care (NY)"},
    {"value": "Firefly Health", "label": "Firefly Health"},
    {"value": "First Choice Health", "label": "First Choice Health"},
    {"value": "First Choice Health Plan of Mississippi", "label": "First Choice Health Plan of Mississippi"},
    {"value": "First Health (Coventry Health Care)", "label": "First Health (Coventry Health Care)"},
    {"value": "FirstCare Health Plans", "label": "FirstCare Health Plans"},
    {"value": "FirstCarolinaCare", "label": "FirstCarolinaCare"},
    {"value": "Florida Blue: Blue Cross Blue Shield of Florida", "label": "Florida Blue: Blue Cross Blue Shield of Florida"},
    {"value": "Florida Community Care", "label": "Florida Community Care"},
    {"value": "Florida Health Care Plans", "label": "Florida Health Care Plans"},
    {"value": "Florida Health Partners", "label": "Florida Health Partners"},
    {"value": "Florida Hospital Healthcare System (FHHS)", "label": "Florida Hospital Healthcare System (FHHS)"},
    {"value": "Florida KidCare", "label": "Florida KidCare"},
    {"value": "Fort Bend County Indigent Health Care", "label": "Fort Bend County Indigent Health Care"},
    {"value": "Fortified Provider Network", "label": "Fortified Provider Network"},
    {"value": "Freedom Health", "label": "Freedom Health"},
    {"value": "Fresenius Health Plans", "label": "Fresenius Health Plans"},
    {"value": "Friday Health Plans", "label": "Friday Health Plans"},
    {"value": "GEHA", "label": "GEHA"},
    {"value": "GEMCare Health Plan", "label": "GEMCare Health Plan"},
    {"value": "GWH-Cigna (formerly Great West Healthcare)", "label": "GWH-Cigna (formerly Great West Healthcare)"},
    {"value": "Galaxy Health", "label": "Galaxy Health"},
    {"value": "Gateway Health", "label": "Gateway Health"},
    {"value": "Geisinger Health Plan", "label": "Geisinger Health Plan"},
    {"value": "General Vision Services (GVS)", "label": "General Vision Services (GVS)"},
    {"value": "GeoBlue", "label": "GeoBlue"},
    {"value": "Georgia Health Advantage", "label": "Georgia Health Advantage"},
    {"value": "Gilsbar 360 Alliance", "label": "Gilsbar 360 Alliance"},
    {"value": "Global Health", "label": "Global Health"},
    {"value": "Gold Coast Health Plan", "label": "Gold Coast Health Plan"},
    {"value": "Golden Rule", "label": "Golden Rule"},
    {"value": "Golden State Medicare Health Plan", "label": "Golden State Medicare Health Plan"},
    {"value": "Green Mountain Care (Vermont)", "label": "Green Mountain Care (Vermont)"},
    {"value": "Group Health Cooperative", "label": "Group Health Cooperative"},
    {"value": "Group Health Cooperative of Eau Claire", "label": "Group Health Cooperative of Eau Claire"},
    {"value": "Group Health Cooperative of South Central Wisconsin", "label": "Group Health Cooperative of South Central Wisconsin"},
    {"value": "Guardian", "label": "Guardian"},
    {"value": "Gundersen Health Plan", "label": "Gundersen Health Plan"},
    {"value": "HAP (Health Alliance Plan)", "label": "HAP (Health Alliance Plan)"},
    {"value": "HAP Midwest Health Plan", "label": "HAP Midwest Health Plan"},
    {"value": "HFN", "label": "HFN"},
    {"value": "HFS Medical Benefits", "label": "HFS Medical Benefits"},
    {"value": "HUSKY Health", "label": "HUSKY Health"},
    {"value": "Hamaspik Choice", "label": "Hamaspik Choice"},
    {"value": "Harken Health", "label": "Harken Health"},
    {"value": "Harmony Health Plan", "label": "Harmony Health Plan"},
    {"value": "Harvard Pilgrim Health Care", "label": "Harvard Pilgrim Health Care"},
    {"value": "Hawaii Medical Assurance Association (HMAA)", "label": "Hawaii Medical Assurance Association (HMAA)"},
    {"value": "Hawaii Medical Service Association (HMSA)", "label": "Hawaii Medical Service Association (HMSA)"},
    {"value": "Health Alliance", "label": "Health Alliance"},
    {"value": "Health Choice Arizona", "label": "Health Choice Arizona"},
    {"value": "Health First (FL)", "label": "Health First (FL)"},
    {"value": "Health First Colorado", "label": "Health First Colorado"},
    {"value": "Health First Health Plans (Florida)", "label": "Health First Health Plans (Florida)"},
    {"value": "Health Net", "label": "Health Net"},
    {"value": "Health New England", "label": "Health New England"},
    {"value": "Health Partners Plans (Pennsylvania)", "label": "Health Partners Plans (Pennsylvania)"},
    {"value": "Health Plan of Nevada", "label": "Health Plan of Nevada"},
    {"value": "Health Plan of San Joaquin", "label": "Health Plan of San Joaquin"},
    {"value": "Health Plan of San Mateo", "label": "Health Plan of San Mateo"},
    {"value": "Health Plus", "label": "Health Plus"},
    {"value": "Health Share of Oregon", "label": "Health Share of Oregon"},
    {"value": "Health Sun", "label": "Health Sun"},
    {"value": "HealthChoice Oklahoma", "label": "HealthChoice Oklahoma"},
    {"value": "HealthChoice of Michigan", "label": "HealthChoice of Michigan"},
    {"value": "HealthFirst (NY)", "label": "HealthFirst (NY)"},
    {"value": "HealthNow", "label": "HealthNow"},
    {"value": "HealthPartners", "label": "HealthPartners"},
    {"value": "HealthScope Benefits", "label": "HealthScope Benefits"},
    {"value": "HealthSmart", "label": "HealthSmart"},
    {"value": "HealthTeam Advantage", "label": "HealthTeam Advantage"},
    {"value": "Healthcare Highways Health Plan", "label": "Healthcare Highways Health Plan"},
    {"value": "Healthlink", "label": "Healthlink"},
    {"value": "Healthy Texas Women", "label": "Healthy Texas Women"},
    {"value": "HealthyCT", "label": "HealthyCT"},
    {"value": "Hear In America", "label": "Hear In America"},
    {"value": "Hennepin Health", "label": "Hennepin Health"},
    {"value": "Heritage Vision Plans", "label": "Heritage Vision Plans"},
    {"value": "Highmark Blue Cross Blue Shield", "label": "Highmark Blue Cross Blue Shield"},
    {"value": "Highmark Blue Cross Blue Shield of Delaware", "label": "Highmark Blue Cross Blue Shield of Delaware"},
    {"value": "Highmark Blue Cross Blue Shield of Western New York", "label": "Highmark Blue Cross Blue Shield of Western New York"},
    {"value": "Highmark Blue Shield", "label": "Highmark Blue Shield"},
    {"value": "Highmark BlueCross BlueShield of West Virginia", "label": "Highmark BlueCross BlueShield of West Virginia"},
    {"value": "Hillsborough Health Care Plan", "label": "Hillsborough Health Care Plan"},
    {"value": "Home State Health Plan", "label": "Home State Health Plan"},
    {"value": "Hometown Health", "label": "Hometown Health"},
    {"value": "Horizon Blue Cross Blue Shield of New Jersey", "label": "Horizon Blue Cross Blue Shield of New Jersey"},
    {"value": "Horizon Blue Cross Blue Shield of New Jersey For Barnabas Health", "label": "Horizon Blue Cross Blue Shield of New Jersey For Barnabas Health"},
    {"value": "Horizon Blue Cross Blue Shield of New Jersey For Novartis", "label": "Horizon Blue Cross Blue Shield of New Jersey For Novartis"},
    {"value": "Horizon NJ Health", "label": "Horizon NJ Health"},
    {"value": "Hudson Health Plan", "label": "Hudson Health Plan"},
    {"value": "Humana", "label": "Humana"},
    {"value": "Humana Behavioral Health (LifeSynch)", "label": "Humana Behavioral Health (LifeSynch)"},
    {"value": "IHC Health Solutions", "label": "IHC Health Solutions"},
    {"value": "IMS (Independent Medical Systems)", "label": "IMS (Independent Medical Systems)"},
    {"value": "IU Health Plans (Indiana University Health)", "label": "IU Health Plans (Indiana University Health)"},
    {"value": "Illinicare Health", "label": "Illinicare Health"},
    {"value": "Illinois' Primary Care Case Management (PCCM)", "label": "Illinois' Primary Care Case Management (PCCM)"},
    {"value": "Imagine Health", "label": "Imagine Health"},
    {"value": "Imperial Health Plan of California", "label": "Imperial Health Plan of California"},
    {"value": "Imperial Insurance Company of Texas", "label": "Imperial Insurance Company of Texas"},
    {"value": "InTotal Health", "label": "InTotal Health"},
    {"value": "Independence Blue Cross", "label": "Independence Blue Cross"},
    {"value": "Independence Care System", "label": "Independence Care System"},
    {"value": "Independent Health", "label": "Independent Health"},
    {"value": "Indiana Medicaid", "label": "Indiana Medicaid"},
    {"value": "Ingham Health Plan", "label": "Ingham Health Plan"},
    {"value": "Inland Empire Health Plan", "label": "Inland Empire Health Plan"},
    {"value": "Innovation Health", "label": "Innovation Health"},
    {"value": "Integra", "label": "Integra"},
    {"value": "Inter Valley Health Plan", "label": "Inter Valley Health Plan"},
    {"value": "InterCommunity Health Network CCO", "label": "InterCommunity Health Network CCO"},
    {"value": "Intergroup Services", "label": "Intergroup Services"},
    {"value": "Iowa MediPASS", "label": "Iowa MediPASS"},
    {"value": "Iowa Total Care", "label": "Iowa Total Care"},
    {"value": "Itasca Medical Care", "label": "Itasca Medical Care"},
    {"value": "Jackson Care Connect", "label": "Jackson Care Connect"},
    {"value": "Jackson Health Plan", "label": "Jackson Health Plan"},
    {"value": "Jai Medical Systems", "label": "Jai Medical Systems"},
    {"value": "Johns Hopkins Employer Health Programs", "label": "Johns Hopkins Employer Health Programs"},
    {"value": "Kaiser Permanente", "label": "Kaiser Permanente"},
    {"value": "Kansas HealthWave", "label": "Kansas HealthWave"},
    {"value": "Kansas Superior Select", "label": "Kansas Superior Select"},
    {"value": "KelseyCare Advantage", "label": "KelseyCare Advantage"},
    {"value": "Keystone First", "label": "Keystone First"},
    {"value": "L.A. Care Health Plan", "label": "L.A. Care Health Plan"},
    {"value": "Land of Lincoln Health", "label": "Land of Lincoln Health"},
    {"value": "Landmark Healthplan", "label": "Landmark Healthplan"},
    {"value": "Lasso Healthcare", "label": "Lasso Healthcare"},
    {"value": "Legacy Health", "label": "Legacy Health"},
    {"value": "Lehigh Valley Health Network Health Plan", "label": "Lehigh Valley Health Network Health Plan"},
    {"value": "Leon Medical Centers Health Plans", "label": "Leon Medical Centers Health Plans"},
    {"value": "Liberty Health Advantage", "label": "Liberty Health Advantage"},
    { "value": "Liberty HealthShare", "label": "Liberty HealthShare" },
    { "value": "Liberty Mutual", "label": "Liberty Mutual" },
    { "value": "LifeWise", "label": "LifeWise" },
    { "value": "Lifestyle Health", "label": "Lifestyle Health" },
    { "value": "Lighthouse Guild", "label": "Lighthouse Guild" },
    { "value": "Lighthouse Health Plan", "label": "Lighthouse Health Plan" },
    { "value": "Lincoln Financial Group", "label": "Lincoln Financial Group" },
    { "value": "Live360 Health Plan", "label": "Live360 Health Plan" },
    { "value": "Longevity Health Plan", "label": "Longevity Health Plan" },
    { "value": "Louisiana Healthcare Connections", "label": "Louisiana Healthcare Connections" },
    { "value": "Lutheran Preferred", "label": "Lutheran Preferred" },
    { "value": "Lyra Health", "label": "Lyra Health" },
    { "value": "MCM Maxcare", "label": "MCM Maxcare" },
    { "value": "MDwise", "label": "MDwise" },
    { "value": "MHNet Behavioral Health", "label": "MHNet Behavioral Health" },
    { "value": "MINES & Associates", "label": "MINES & Associates" },
    { "value": "MMM of Florida (Medicare and Much More)", "label": "MMM of Florida (Medicare and Much More)" },
    { "value": "MO HealthNet", "label": "MO HealthNet" },
    { "value": "MOAA (Miltary Officers Association of America)", "label": "MOAA (Miltary Officers Association of America)" },
    { "value": "MVP Health Care", "label": "MVP Health Care" },
    { "value": "Magellan Health", "label": "Magellan Health" },
    { "value": "MagnaCare", "label": "MagnaCare" },
    { "value": "Magnolia Health Plan", "label": "Magnolia Health Plan" },
    { "value": "Mail Handlers Benefit Plan", "label": "Mail Handlers Benefit Plan" },
    { "value": "MaineCare", "label": "MaineCare" },
    { "value": "Managed Health Network (MHN)", "label": "Managed Health Network (MHN)" },
    { "value": "Managed Health Services (Indiana)", "label": "Managed Health Services (Indiana)" },
    { "value": "Managed Health Services (Wisconsin)", "label": "Managed Health Services (Wisconsin)" },
    { "value": "Managed HealthCare Northwest", "label": "Managed HealthCare Northwest" },
    { "value": "March Vision Care", "label": "March Vision Care" },
    { "value": "Martin's Point HealthCare", "label": "Martin's Point HealthCare" },
    { "value": "Maryland Medical Assistance (Medicaid)", "label": "Maryland Medical Assistance (Medicaid)" },
    { "value": "Maryland Physicians Care", "label": "Maryland Physicians Care" },
    { "value": "Mass General Brigham Health Plan", "label": "Mass General Brigham Health Plan" },
    { "value": "MassHealth", "label": "MassHealth" },
    { "value": "Massachusetts Laborers' Health & Welfare Fund", "label": "Massachusetts Laborers' Health & Welfare Fund" },
    { "value": "Mayo Medical Plan", "label": "Mayo Medical Plan" },
    { "value": "McLaren Health Plan", "label": "McLaren Health Plan" },
    { "value": "MedStar Family Choice", "label": "MedStar Family Choice" },
    { "value": "MedStar Select", "label": "MedStar Select" },
    { "value": "Medi-Cal", "label": "Medi-Cal" },
    { "value": "MediGold", "label": "MediGold" },
    { "value": "MediPass", "label": "MediPass" },
    { "value": "Medica", "label": "Medica" },
    { "value": "Medica HealthCare Plans (Florida)", "label": "Medica HealthCare Plans (Florida)" },
    { "value": "Medicaid", "label": "Medicaid" },
    { "value": "Medical Associates Health Plans", "label": "Medical Associates Health Plans" },
    { "value": "Medical Eye Services (MES Vision)", "label": "Medical Eye Services (MES Vision)" },
    { "value": "Medical Mutual", "label": "Medical Mutual" },
    { "value": "Medicare", "label": "Medicare" },
    { "value": "Memorial Healthcare System", "label": "Memorial Healthcare System" },
    { "value": "Memorial Hermann", "label": "Memorial Hermann" },
    { "value": "Mercy Care", "label": "Mercy Care" },
    { "value": "Meridian Health Plan", "label": "Meridian Health Plan" },
    { "value": "Meritain Health", "label": "Meritain Health" },
    { "value": "MetLife", "label": "MetLife" },
    { "value": "MetroHealth", "label": "MetroHealth" },
    { "value": "MetroPlus Health Plan", "label": "MetroPlus Health Plan" },
    { "value": "Miami Children's Health Plan", "label": "Miami Children's Health Plan" },
    { "value": "Michigan Complete Health", "label": "Michigan Complete Health" },
    { "value": "Michigan No-Fault", "label": "Michigan No-Fault" },
    { "value": "Minuteman Health", "label": "Minuteman Health" },
    { "value": "Mississippi Division of Medicaid", "label": "Mississippi Division of Medicaid" },
    { "value": "Missouri Care", "label": "Missouri Care" },
    { "value": "Moda Health", "label": "Moda Health" },
    { "value": "Molina Healthcare", "label": "Molina Healthcare" },
    { "value": "Montana Health Cooperative", "label": "Montana Health Cooperative" },
    { "value": "Montefiore HMO", "label": "Montefiore HMO" },
    { "value": "MoreCare", "label": "MoreCare" },
    { "value": "Mountain Health Co-Op", "label": "Mountain Health Co-Op" },
    { "value": "Multiplan PHCS", "label": "Multiplan PHCS" },
    { "value": "Mutual of Omaha", "label": "Mutual of Omaha" },
    { "value": "NALC Health Benefit Plan", "label": "NALC Health Benefit Plan" },
    { "value": "NECA/IBEW Family Medical Care Plan", "label": "NECA/IBEW Family Medical Care Plan" },
    { "value": "NY State No-Fault", "label": "NY State No-Fault" },
    { "value": "NY: YourCare Health Plan", "label": "NY: YourCare Health Plan" },
    { "value": "National Congress of Employers (NCE)", "label": "National Congress of Employers (NCE)" },
    { "value": "National Vision Administrators", "label": "National Vision Administrators" },
    { "value": "Nationwide", "label": "Nationwide" },
    { "value": "Navajo Nation", "label": "Navajo Nation" },
    { "value": "Nebraska Total Care (Heritage Health)", "label": "Nebraska Total Care (Heritage Health)" },
    { "value": "Neighborhood Health Plan (Massachusetts)", "label": "Neighborhood Health Plan (Massachusetts)" },
    { "value": "Neighborhood Health Plan of Rhode Island", "label": "Neighborhood Health Plan of Rhode Island" },
    { "value": "Neighborhood Health Providers (NY)", "label": "Neighborhood Health Providers (NY)" },
    { "value": "Network Health Plan", "label": "Network Health Plan" },
    { "value": "Nevada Preferred", "label": "Nevada Preferred" },
    { "value": "New Directions Behavioral Health", "label": "New Directions Behavioral Health" },
    { "value": "New Hampshire Healthy Families", "label": "New Hampshire Healthy Families" },
    { "value": "New Mexico Health Connections", "label": "New Mexico Health Connections" },
    { "value": "New York Hotel Trades Council", "label": "New York Hotel Trades Council" },
    { "value": "NextLevelHealth", "label": "NextLevelHealth" },
    { "value": "Nippon Life Benefits", "label": "Nippon Life Benefits" },
    { "value": "North Shore LIJ CareConnect", "label": "North Shore LIJ CareConnect" },
    { "value": "Northland PACE", "label": "Northland PACE" },
    { "value": "Northwell Direct", "label": "Northwell Direct" },
    { "value": "NovaNet", "label": "NovaNet" },
    { "value": "OSU Health Plan", "label": "OSU Health Plan" },
    { "value": "Ohio Health Choice", "label": "Ohio Health Choice" },
    { "value": "OhioHealthy", "label": "OhioHealthy" },
    { "value": "On Lok Lifeways", "label": "On Lok Lifeways" },
    { "value": "On Lok Lifeways (PACE)", "label": "On Lok Lifeways (PACE)" },
    { "value": "OneNet PPO", "label": "OneNet PPO" },
    { "value": "Opticare of Utah", "label": "Opticare of Utah" },
    { "value": "Optima Health", "label": "Optima Health" },
    { "value": "Optimum HealthCare", "label": "Optimum HealthCare" },
    { "value": "Optum Health", "label": "Optum Health" },
    { "value": "Oscar Health Insurance Co.", "label": "Oscar Health Insurance Co." },
    { "value": "PA Health and Wellness", "label": "PA Health and Wellness" },
    { "value": "PBA (Patrolmen's Benefit Association)", "label": "PBA (Patrolmen's Benefit Association)" },
    { "value": "POMCO", "label": "POMCO" },
    { "value": "Pacific Health Alliance", "label": "Pacific Health Alliance" },
    { "value": "PacificSource Health Plans", "label": "PacificSource Health Plans" },
    { "value": "Palmetto GBA", "label": "Palmetto GBA" },
    { "value": "Pan-American Life Insurance Group", "label": "Pan-American Life Insurance Group" },
    { "value": "Paradigm Senior Care Advantage", "label": "Paradigm Senior Care Advantage" },
    { "value": "Paramount Healthcare", "label": "Paramount Healthcare" },
    { "value": "Parkland Community Health Plan", "label": "Parkland Community Health Plan" },
    { "value": "Parkview Total Health", "label": "Parkview Total Health" },
    { "value": "Partners Health Plan", "label": "Partners Health Plan" },
    { "value": "Partnership HealthPlan of California", "label": "Partnership HealthPlan of California" },
    { "value": "Passport Health Plan (Kentucky)", "label": "Passport Health Plan (Kentucky)" },
    { "value": "Passport To Health (Montana Medicaid)", "label": "Passport To Health (Montana Medicaid)" },
    { "value": "Patient 1st (Alabama Medicaid)", "label": "Patient 1st (Alabama Medicaid)" },
    { "value": "Peach State Health Plan", "label": "Peach State Health Plan" },
    { "value": "PeachCare for Kids", "label": "PeachCare for Kids" },
    { "value": "PennCare", "label": "PennCare" },
    { "value": "Peoples Health", "label": "Peoples Health" },
    { "value": "Phoenix Health Plan", "label": "Phoenix Health Plan" },
    { "value": "Physician Assured Access System", "label": "Physician Assured Access System" },
    { "value": "Physicians Eyecare Plan", "label": "Physicians Eyecare Plan" },
    { "value": "Physicians Health Plan", "label": "Physicians Health Plan" },
    { "value": "Physicians Health Plan of Northern Indiana, Inc.", "label": "Physicians Health Plan of Northern Indiana, Inc." },
    { "value": "PhysiciansCare", "label": "PhysiciansCare" },
    { "value": "Piedmont Community Health Plan", "label": "Piedmont Community Health Plan" },
    { "value": "Piedmont WellStar Health Plans", "label": "Piedmont WellStar Health Plans" },
    { "value": "Positive Health Care", "label": "Positive Health Care" },
    { "value": "Preferential Care Network", "label": "Preferential Care Network" },
    { "value": "Preferred Care Partners", "label": "Preferred Care Partners" },
    { "value": "PreferredOne", "label": "PreferredOne" },
    { "value": "Premera Blue Cross", "label": "Premera Blue Cross" },
    { "value": "Premier Health Plan", "label": "Premier Health Plan" },
    { "value": "Presbyterian Health Plan/Presbyterian Insurance Company", "label": "Presbyterian Health Plan/Presbyterian Insurance Company" },
    { "value": "Prestige Health Choice", "label": "Prestige Health Choice" },
    { "value": "Primary Care Case Management (North Dakota Medicaid)", "label": "Primary Care Case Management (North Dakota Medicaid)" },
    { "value": "Prime Health Services, Inc", "label": "Prime Health Services, Inc" },
    { "value": "Prime Healthcare", "label": "Prime Healthcare" },
    { "value": "PrimeWest Health", "label": "PrimeWest Health" },
    { "value": "Principal Financial Group", "label": "Principal Financial Group" },
    { "value": "Priority Health", "label": "Priority Health" },
    { "value": "Priority Partners", "label": "Priority Partners" },
    { "value": "ProCare Advantage", "label": "ProCare Advantage" },
    { "value": "Progressive", "label": "Progressive" },
    { "value": "Prominence Health Plan", "label": "Prominence Health Plan" },
    { "value": "ProviDRs Care (WPPA)", "label": "ProviDRs Care (WPPA)" },
    { "value": "Providence Health Plans", "label": "Providence Health Plans" },
    { "value": "Provider Partners Health Plan", "label": "Provider Partners Health Plan" },
    { "value": "PruittHealth Premier", "label": "PruittHealth Premier" },
    { "value": "Public Aid (Illinois Medicaid)", "label": "Public Aid (Illinois Medicaid)" },
    { "value": "Public Employees Health Program (PEHP)", "label": "Public Employees Health Program (PEHP)" },
    { "value": "Puget Sound Electrical Workers Trusts", "label": "Puget Sound Electrical Workers Trusts" },
    { "value": "QualCare", "label": "QualCare" },
    { "value": "QualChoice Arkansas", "label": "QualChoice Arkansas" },
    { "value": "Quality Health Plans of New York", "label": "Quality Health Plans of New York" },
    { "value": "Quartz", "label": "Quartz" },
    { "value": "Quest Behavioral Health", "label": "Quest Behavioral Health" },
    { "value": "Quiktrip", "label": "Quiktrip" },
    { "value": "Regence Blue Cross Blue Shield", "label": "Regence Blue Cross Blue Shield" },
    { "value": "Regence Blue Shield of Washington", "label": "Regence Blue Shield of Washington" },
    { "value": "Reliance Medicare Advantage", "label": "Reliance Medicare Advantage" },
    { "value": "Renaissance", "label": "Renaissance" },
    { "value": "RiverLink Health", "label": "RiverLink Health" },
    { "value": "RiverSpring Health Plans", "label": "RiverSpring Health Plans" },
    { "value": "RiverSpring at Home", "label": "RiverSpring at Home" },
    { "value": "Riverside Health", "label": "Riverside Health" },
    { "value": "Rockefeller Health Plan", "label": "Rockefeller Health Plan" },
    { "value": "Rocky Mountain Health Plans", "label": "Rocky Mountain Health Plans" },
    { "value": "SAG AFTRA Health Plan", "label": "SAG AFTRA Health Plan" },
    { "value": "SAMBA", "label": "SAMBA" },
    { "value": "SCAN Health Plan", "label": "SCAN Health Plan" },
    { "value": "SIHO Insurance Services", "label": "SIHO Insurance Services" },
    { "value": "SSM Health Care", "label": "SSM Health Care" },
    { "value": "Sagamore Health Network", "label": "Sagamore Health Network" },
    { "value": "Samaritan Health Plan Operations", "label": "Samaritan Health Plan Operations" },
    { "value": "San Francisco Health Plan", "label": "San Francisco Health Plan" },
    { "value": "Sana", "label": "Sana" },
    { "value": "Sanford Health Plan", "label": "Sanford Health Plan" },
    { "value": "Santa Clara Family Health Plan", "label": "Santa Clara Family Health Plan" },
    { "value": "Security Health Plan of Wisconsin, Inc.", "label": "Security Health Plan of Wisconsin, Inc." },
    { "value": "Select Care", "label": "Select Care" },
    { "value": "Select Health Network", "label": "Select Health Network" },
    { "value": "Select Health of South Carolina", "label": "Select Health of South Carolina" },
    { "value": "SelectHealth", "label": "SelectHealth" },
    { "value": "Sendero Health Plans", "label": "Sendero Health Plans" },
    { "value": "Senior Dimensions", "label": "Senior Dimensions" },
    { "value": "Senior Whole Health", "label": "Senior Whole Health" },
    { "value": "Seton Health Plan", "label": "Seton Health Plan" },
    { "value": "Sharp Health Plan", "label": "Sharp Health Plan" },
    { "value": "Sierra Health and Life", "label": "Sierra Health and Life" },
    { "value": "SightCare", "label": "SightCare" },
    { "value": "SilverSummit Healthplan", "label": "SilverSummit Healthplan" },
    { "value": "Simply Healthcare", "label": "Simply Healthcare" },
    { "value": "Simpra Advantage", "label": "Simpra Advantage" },
    { "value": "Solis Health Plans", "label": "Solis Health Plans" },
    { "value": "Solstice", "label": "Solstice" },
    { "value": "Sonder Health Plans", "label": "Sonder Health Plans" },
    { "value": "SoonerCare (Oklahoma Medicaid)", "label": "SoonerCare (Oklahoma Medicaid)" },
    { "value": "Soundpath Health", "label": "Soundpath Health" },
    { "value": "South Country Health Alliance", "label": "South Country Health Alliance" },
    { "value": "South Florida Community Care Network", "label": "South Florida Community Care Network" },
    { "value": "Southwestern Health Resources (SWHR)", "label": "Southwestern Health Resources (SWHR)" },
    { "value": "Spectera", "label": "Spectera" },
    { "value": "Standard Life and Accident Insurance Company", "label": "Standard Life and Accident Insurance Company" },
    { "value": "Stanford Health Care Advantage", "label": "Stanford Health Care Advantage" },
    { "value": "State Farm®", "label": "State Farm®" },
    { "value": "Staywell Insurance", "label": "Staywell Insurance" },
    { "value": "Steward Health Care Network - Health Choice Arizona", "label": "Steward Health Care Network - Health Choice Arizona" },
    { "value": "Steward Health Choice", "label": "Steward Health Choice" },
    { "value": "Stratose", "label": "Stratose" },
    { "value": "SummaCare", "label": "SummaCare" },
    { "value": "Summit Community Care", "label": "Summit Community Care" },
    { "value": "Sunflower Health Plan", "label": "Sunflower Health Plan" },
    { "value": "Sunrise Advantage Plan", "label": "Sunrise Advantage Plan" },
    { "value": "Sunshine Health", "label": "Sunshine Health" },
    { "value": "Superior HealthPlan", "label": "Superior HealthPlan" },
    { "value": "Superior Vision", "label": "Superior Vision" },
    { "value": "Surest Health Plans (formerly Bind)", "label": "Surest Health Plans (formerly Bind)" },
    { "value": "Sutter Health Plus", "label": "Sutter Health Plus" },
    { "value": "SutterSelect", "label": "SutterSelect" },
    { "value": "TakeCare", "label": "TakeCare" },
    { "value": "Teachers Health Trust", "label": "Teachers Health Trust" },
    { "value": "TestInsuranceTest", "label": "TestInsuranceTest" },
    { "value": "TexanPlus", "label": "TexanPlus" },
    { "value": "Texas Children's Health Plan", "label": "Texas Children's Health Plan" },
    { "value": "Texas Health Aetna", "label": "Texas Health Aetna" },
    { "value": "Texas Independence Health Plan (TIHP)", "label": "Texas Independence Health Plan (TIHP)" },
    { "value": "Texas Kids First", "label": "Texas Kids First" },
    { "value": "The HSC Health Care System", "label": "The HSC Health Care System" },
    { "value": "The Hartford", "label": "The Hartford" },
    { "value": "The Health Plan of the Upper Ohio Valley, Inc.", "label": "The Health Plan of the Upper Ohio Valley, Inc." },
    { "value": "Three Rivers Providers Network (TRPN)", "label": "Three Rivers Providers Network (TRPN)" },
    { "value": "Total Health Care", "label": "Total Health Care" },
    { "value": "Touchstone", "label": "Touchstone" },
    { "value": "Transamerica", "label": "Transamerica" },
    { "value": "Travelers", "label": "Travelers" },
    { "value": "Tricare", "label": "Tricare" },
    { "value": "Trillium Community Health Plan", "label": "Trillium Community Health Plan" },
    { "value": "Trilogy Health Insurance", "label": "Trilogy Health Insurance" },
    { "value": "Triple-S Salud: Blue Cross Blue Shield of Puerto Rico", "label": "Triple-S Salud: Blue Cross Blue Shield of Puerto Rico" },
    { "value": "Triwest Healthcare Alliance", "label": "Triwest Healthcare Alliance" },
    { "value": "Troy Health", "label": "Troy Health" },
    { "value": "TrueHealth New Mexico", "label": "TrueHealth New Mexico" },
    { "value": "Trusted Health Plan", "label": "Trusted Health Plan" },
    { "value": "Tuality Health Alliance", "label": "Tuality Health Alliance" },
    { "value": "Tufts Health Freedom Plan", "label": "Tufts Health Freedom Plan" },
    { "value": "Tufts Health Plan", "label": "Tufts Health Plan" },
    { "value": "UCHP (University of Chicago Health Plan)", "label": "UCHP (University of Chicago Health Plan)" },
    { "value": "UCare", "label": "UCare" },
    { "value": "UHA Health Insurance", "label": "UHA Health Insurance" },
    { "value": "UPMC Health Plan", "label": "UPMC Health Plan" },
    { "value": "US Family Health Plan", "label": "US Family Health Plan" },
    { "value": "US Health Group", "label": "US Health Group" },
    { "value": "USA Managed Care Organization", "label": "USA Managed Care Organization" },
    { "value": "USAble Mutual Insurance Company", "label": "USAble Mutual Insurance Company" },
    { "value": "Ultimate Health Plans", "label": "Ultimate Health Plans" },
    { "value": "Umpqua Health Alliance", "label": "Umpqua Health Alliance" },
    { "value": "UniCare", "label": "UniCare" },
    { "value": "Uniform Medical Plan", "label": "Uniform Medical Plan" },
    { "value": "Union Eye Care", "label": "Union Eye Care" },
    { "value": "Union Health Services, Inc", "label": "Union Health Services, Inc" },
    { "value": "Union Plans", "label": "Union Plans" },
    { "value": "United American", "label": "United American" },
    { "value": "United Behavioral Health", "label": "United Behavioral Health" },
    { "value": "UnitedHealthOne", "label": "UnitedHealthOne" },
    { "value": "UnitedHealthcare", "label": "UnitedHealthcare" },
    { "value": "UnitedHealthcare Community Plan", "label": "UnitedHealthcare Community Plan" },
    { "value": "UnitedHealthcare Oxford", "label": "UnitedHealthcare Oxford" },
    { "value": "Unity Health Insurance", "label": "Unity Health Insurance" },
    { "value": "Univera Healthcare", "label": "Univera Healthcare" },
    { "value": "Universal American", "label": "Universal American" },
    { "value": "Universal Healthcare", "label": "Universal Healthcare" },
    { "value": "University Hospitals (Health Design Plus)", "label": "University Hospitals (Health Design Plus)" },
    { "value": "University Physician Network (UPN)", "label": "University Physician Network (UPN)" },
    { "value": "University of Arizona Health Plans", "label": "University of Arizona Health Plans" },
    { "value": "University of Maryland Health Advantage", "label": "University of Maryland Health Advantage" },
    { "value": "University of Maryland Health Partners", "label": "University of Maryland Health Partners" },
    { "value": "University of St. Mary of the Lake - Mundelein Seminary", "label": "University of St. Mary of the Lake - Mundelein Seminary" },
    { "value": "University of Utah Health Plans", "label": "University of Utah Health Plans" },
    { "value": "Upper Peninsula Health Plan", "label": "Upper Peninsula Health Plan" },
    { "value": "VNS Choice Health Plans", "label": "VNS Choice Health Plans" },
    { "value": "VSP", "label": "VSP" },
    { "value": "Valley Health Plan", "label": "Valley Health Plan" },
    { "value": "Valor Health Plan", "label": "Valor Health Plan" },
    { "value": "Vantage Health Plan, Inc.", "label": "Vantage Health Plan, Inc." },
    { "value": "Ventura County Health Care Plan", "label": "Ventura County Health Care Plan" },
    { "value": "Vibra Health Plan", "label": "Vibra Health Plan" },
    { "value": "VillageCareMax", "label": "VillageCareMax" },
    { "value": "Virginia Coordinated Care (VCC)", "label": "Virginia Coordinated Care (VCC)" },
    { "value": "Virginia Health Network", "label": "Virginia Health Network" },
    { "value": "Virginia Premier Health Plan", "label": "Virginia Premier Health Plan" },
    { "value": "Vision Benefits of America", "label": "Vision Benefits of America" },
    { "value": "Vision Care Direct", "label": "Vision Care Direct" },
    { "value": "Vision Plan of America", "label": "Vision Plan of America" },
    { "value": "Viva Health Plan", "label": "Viva Health Plan" },
    { "value": "Vivida Health", "label": "Vivida Health" },
    { "value": "Volusia Health Network", "label": "Volusia Health Network" },
    { "value": "Vytra", "label": "Vytra" },
    { "value": "WEA Trust", "label": "WEA Trust" },
    { "value": "WPS Health Plan", "label": "WPS Health Plan" },
    { "value": "WellFirst Health", "label": "WellFirst Health" },
    { "value": "WellSense Health Plan", "label": "WellSense Health Plan" },
    { "value": "Wellcare", "label": "Wellcare" },
    { "value": "Wellmark Blue Cross Blue Shield", "label": "Wellmark Blue Cross Blue Shield" },
    { "value": "West Virginia Senior Advantage", "label": "West Virginia Senior Advantage" },
    { "value": "Western Health Advantage", "label": "Western Health Advantage" },
    { "value": "Western Sky Community Care", "label": "Western Sky Community Care" },
    { "value": "Willamette Valley Community Health", "label": "Willamette Valley Community Health" },
    { "value": "Workers' Compensation", "label": "Workers' Compensation" },
    { "value": "Yamhill Community Care Organization", "label": "Yamhill Community Care Organization" },
    { "value": "Zenith", "label": "Zenith" },
    { "value": "Zing Health", "label": "Zing Health" }
];